### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Alkalinee** [AnguisCaptor/StreamLibrary#1]
Under which license am I allowed to use your library? You did an awesome job here btw :)

**Comment by AnguisCaptor** [comment]
Thanks :)
Sorry for the delayed answer, It's under the GPL license.

**Comment by Alkalinee** [comment]
@AnguisCaptor Uhm, okay, I'm a little bit confused. You published your code on hf but GPL is a pretty unusual license for code which can be used by others. GPL means that I'll have to publish the whole code of my application also under GPL which is impossible for me because that means that everybody is allowed to republish my application. Are you sure about it? I really like GPL for free software, but in my opinion it's a pretty bad license for libraries. Most libraries are licensed under MIT.

**Comment by AnguisCaptor** [comment]
Yeah you're right, I never gave a real thought which I would choose
It's not anywhere in the code either which license I actually use
It's under MIT now ;)

**Comment by Alkalinee** [comment]
Thank you :)
